### ISSUE TITLE
Imported armature not working well with animations

### ISSUE THREAD

**Issue by Heaverno** [BadDogSkyrim/PyNifly#36]
please skip first 2 sections and just go to third section directly. 
-----------------------------
any bone with name like Lxxxx or Rxxxx will be renamed to xxxx.L or xxxx.R. 
this is fitting blender habbit but I just can't apply anim to armature unless I change these names manually or by code. 
wishing to have a checkbox to enable the function :)
 
after checking the code I found out that this is not a issue but a feature, so I wrote a file with blender text editor to solve the naming problem. 
so the nearest animating tutor for FO4 I can find is F4AK, which is finally released in 2016, and that's a bit too old, there are many different naming conflicts bwtween skeleton in F4AK's outputted .fbx anims and skeleton we are using now, but this is not a big problem as it can be easily fixed in blender.
what's confusing me now, is the anim still looks weird after the problem above solved.
I downloaded CBBE modder file and game file and imported them seperately with blender fbx importer and pynifly.
pynifly imported armature is not working good. 
I will give a .blend file to show the result. It seems like a result of wrong bone base rotation, but after I tried all bone axis combination importing anim.fbx, none of them give a correct result. 
so i assume it a none unified problem, so far I can't find a clue to solve it. 
PS：I'll seperate talking and files cuz github keeps resetting link.
        and I dont think it's caused by nif files cuz they work in game(should be working, I've just played fo4 for story ).

**Comment by Heaverno** [comment]
[files.zip](https://github.com/BadDogSkyrim/PyNifly/files/6719825/files.zip)
files mentioned above
qwq

**Comment by Heaverno** [comment]
so after I fixed the 2 questions above by myself, anims.fbx I exported with F4AK still make mesh imported with nifly warping. 
and I found out another problem: some bones seems to get correct skin weight attached as I moved them, but it shows a totally blue in weight paint mode, which means we can't operate them in blender. 
I used nif file in CBBE that one can download anywhere, just imported and havent done anything to it. 
I think it's way out of my capability but I'm convinced this is critical to get anims work well before nifly can handle hkx directly (maybe).

**Comment by Heaverno** [comment]
although I dont like max, I'll have to download one to get a correct armature.

**Comment by BadDogSkyrim** [comment]
Sorry I missed this whole thread--and now I see it's marked closed. But the base issue is still there, right, that renaming the bones messes up the animation? I can certainly make that an option. 

As for the various issues, things like the bone affecting the mesh but showing blue--the bone weights *are* the vertex group weights, so they have to match, but there's lots of ways you can not be seeing what you thought you were seeing in blender. Also I know there was an issue with transforms which I've now fixed, but I'm not sure that fix applies to the bones. If you want to work through this I'm happy to do so now that I see the message.

I'm going to re-open this for now so I don't lose it.

**Comment by BadDogSkyrim** [comment]
Implemented a mechanism to not rename the bones, but it seems to have issues right now. Closing this because that bug is reported in another ticket.
